### ISSUE TITLE
Permision denied when transferring via ssh

### ISSUE THREAD

**Issue by ijpulidos** [ruediste/btrbck#13]
I configured an app repository to make a PUSH to a remote server via SSH. I can login to the remote server without password using ssh keys. But when I run a btrbck push to the remote server I get

```
# btrbck push -c stream user@remote.server /path/in/remote/server
Permission denied (publickey).
Exception in thread "main" java.lang.RuntimeException: java.io.EOFException
        at com.github.ruediste1.btrbck.SnapshotTransferService.push(SnapshotTransferService.java:213)
        at com.github.ruediste1.btrbck.cli.CliMain.cmdPush(CliMain.java:342)
        at com.github.ruediste1.btrbck.cli.CliMain.processCommand(CliMain.java:133)
        at com.github.ruediste1.btrbck.cli.CliMain.doMain(CliMain.java:113)
        at com.github.ruediste1.btrbck.cli.CliMain.main(CliMain.java:100)
Caused by: java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2351)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2820)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:302)
        at com.github.ruediste1.btrbck.Util.read(Util.java:149)
        at com.github.ruediste1.btrbck.SnapshotTransferService.push(SnapshotTransferService.java:201)
        ... 4 more
```

I don't understand why is this happening, I'm running btrbck as root and this is the same user that can login to the remote server passwordless. The same happens when I try to do it automatically via btrbck process command My repository.xml is as follows

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<applicationStreamRepository version="1">

<!-- The following is a sample sync configuration -->
  <syncConfiguration
    direction="PUSH"
    sshTarget="user@remote.server"
    remoteRepoLocation="/path/in/remote/server"
    createRemoteIfNecessary="true"
    streamPatterns="*"/>

</applicationStreamRepository>
```

**Comment by Polve** [comment]
Is the key protected via password?
Maybe you usually use the ssh agent for not entering each time the passphrase.

**Comment by ijpulidos** [comment]
No, I just do ssh user@remote.server with my root user in localhost (this is the same user running btrbck) and I get the shell directly, no password and no config file for ssh that does stuff automatically. I still don't have a clue what could be happening.

**Comment by ijpulidos** [comment]
Ok, I solved it by using a config file in my .ssh/ directory for ssh where I added an alias for the server and a default user and it's working now. I suspect (not sure) this is due to some limitation in the SSH Java lib used in btrbck. Therefore I added something like the following in my .ssh/config:

```
Host alias
   HostName remote.server
   User user
```
